pages:
  gcp:
    url: https://status.cloud.google.com
    enable: false
  newrelic:
    url: https://status.newrelic.com/?format=json
    enable: true
  github:
    url: https://www.githubstatus.com
    json_url: https://www.githubstatus.com/?format=json
    enable: true
  codefresh:
    url: https://status.codefresh.io
    enable: false
  aws:
    url: https://status.aws.amazon.com
    enable: false
  nearmap:
    url: https://status.nearmap.com/
    enable: false
  cloudflare:
    url: https://www.cloudflarestatus.com/
    json_url: https://www.cloudflarestatus.com/?format=json
    enable: false

status:
  success:
    - "available"
    - "operational"
    - "service is operating normally"
  warning:
    - "service degradation"
    - "partial outage"
    - "under maintenance"
    - "disruption"
  error:
    - "no operational"
    - "service disruption"

status_color:
  default: yellow
  success: green
  warning: yellow
  error: red  
  
